### ISSUE TITLE
Generate key events to thwart those stupid JS checkers

### ISSUE THREAD

**Issue by madduck** [passff/passff#251] opened 2017-11-22 12:05 UTC
Pages like pizza.de had some unbelievably "smart" folks implement JavaScript to ensure that login and password must be typed, not just filled: unless you actually generate a key event on those form fields by typing, it'll pretend that the form fields remain empty and ask you to provide a login and password.

I've tried to disable the JavaScript responsible for this with TamperMonkey, but have had no success.

So this got me thinking: couldn't PassFF generate key events to fill the form fields, rather than just plastering the data into the DOM?

**Comment by tuxor1337** [comment] 2017-11-22 12:10
Duplicate of #182 (fixed in latest Github code).

**Closed by tuxor1337** 2017-11-22 12:10 UTC
Labels: duplicate

**Comment by madduck** [comment] 2017-11-22 12:18
Oh, I'm sorry I missed the duplicate. I did go through all issues, but…
