### ISSUE TITLE
Error: Specified native messaging host not found.

### ISSUE THREAD

**Issue by rpolasek** [passff/passff#255] opened 2017-12-18 10:21 UTC
hello,

it works well in firefox 56 but not in chromium Version 63.0.3239.84 (Developer Build) (64-bit)

$ which pass
/usr/bin/pass

$ ./install_host_app.sh --local chromium
Installing Chromium host config
Native messaging host for Chromium has been installed to /home/me/.config/chromium/NativeMessagingHosts.

$ ls -la ~/.config/chromium/NativeMessagingHosts/
total 16
drwxr-xr-x  2 me users 4096 Dec 18 11:11 .
drwx------ 20 me users 4096 Dec 18 11:18 ..
-rw-r--r--  1 me users  227 Dec 18 11:11 passff.json
-rwxr-xr-x  1 me users 1920 Dec 18 11:11 passff.py

**Comment by tuxor1337** [comment] 2017-12-20 22:04
Closing this as a duplicate of #105

**Closed by tuxor1337** 2017-12-20 22:04 UTC
Labels: duplicate
