### ISSUE TITLE
URL in third line (without prefix, but with protocol)

### ISSUE THREAD

**Issue by ltecheroffical** [passff/passff#562] opened 2024-02-13 08:05 UTC
### Versions
- Operating system: MacOS
- Browser: Firefox 122.0.1
- PassFF: 1.16
- Host app: ???

Status line output: `[hh:mm:ss] show -> (0)`

### Observations

- Output of `pass`: 
- Your preferences
  - In PassFF: 
  - In the host app `passff.py`: 
- Messages in the web console: (None)

When copying the password, everything seems fine until you copy the login info, as shown in the docs:

An entry like this is named "test"

```
Password123
Username
```

It is supposed to copy like this:

Password: Password123
Login: Username

However, the bug copies an entry with the same format as this:

Password: Password123
Login: test
---

### Steps to reproduce the issue
1. Create a simple entry with the username and password as usual but no labels
2. Try to copy the login information using PassFF
3. The login information should be the same as the entry name if done correctly.

### Actual behaviour

What I get is details like this:

Password: Password123
Login: test

### Expected behaviour

What's expected is details like these:

Password: Password123
Login: Username

**Comment by ltecheroffical** [comment] 2024-02-13 21:35
Also the originization scheme requirement doesn't work with single file because you can copy entire lines of entries but no one wants an output like this "URL: example.com"

**Comment by tuxor1337** [comment] 2024-02-14 20:08
I can't reproduce the behavior that you described. Following your instructions I created an entry `/test` with the following contents:
```
Password123
Username
```
When I click on the entry in PassFF and select "Copy login", the token "Username" is copied to clipboard, as expected. I assume that you did not actually test your own instructions...?

Maybe your entry contains a line with a colon (":"). In that case, PassFF assumes that the entry follows the keyword-value format.

**Comment by ltecheroffical** [comment] 2024-02-14 20:16
After testing I found out it only breaks when there is a url at the bottom

**Comment by tuxor1337** [comment] 2024-02-14 20:18
Yes, probably because the URL contains a colon, as I said and as is documented in the README:

> If there are no colons (:) on any of the lines, and there are at least 2 lines, then the first two lines are assumed to contain the password and login name respectively:

**Comment by ltecheroffical** [comment] 2024-02-14 20:20
That does nuke the https:// ensuring a secure connection so maybe that oversight should be patched

**Comment by tuxor1337** [comment] 2024-06-03 21:06
Fixed in 2f48caa

**Closed by tuxor1337** 2024-06-03 21:06 UTC
Labels: enhancement
