### ISSUE TITLE
Version 1.0.3linux broken

### ISSUE THREAD

**Issue by mowgli** [passff/passff#234] opened 2017-09-27 18:04 UTC
With version 1.0.3linux, no text is wisible in buttons or config tabs anymore. There is no way to use this version with all texts wiped out.

**Comment by tuxor1337** [comment] 2017-09-27 21:22
I cannot reproduce this. Which version of Firefox do you use? Which language? Any other extensions running in parallel? Have you tried with a fresh Firefox profile?

**Comment by mowgli** [comment] 2017-09-28 06:31
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Am Mi den 27. Sep 2017 um 22:22 schrieb Thomas Vogt:
> I cannot reproduce this. Which version of Firefox do you use? Which language? Any other extensions running in parallel? Have you tried with a fresh Firefox profile?

- - FF 55.0.3
- - de_DE

Well, sure, it is not possible to run FF without several addons to
secure it.

However, 1.0.1 work well and when I look to the changes from 1.0.1 to
1.0.3, I see that the selectors for strings did chanche on many places
from "." to "_".

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAlnMlzEACgkQpnwKsYAZ
9qwHbgv/aSgOHou+c7R7Ewe/8y/kawuoES4bhB0SGqNF29mwSBdyHAl5aAZe04DS
W9x4W0eFCxEqTHSbIRjXuLJ67RLcfjmmEcwEDziDRkVw3Nl80rmRltJ1JAExRdua
h/5IUsZeBUUS8N5Vl5Yq0NKzQdxnNlQKXlSTXuw5HHiE0ejywCI9Mz6NwE+9qslp
3EFpKzoGpSEro3bPAXy6S+rHGi0eWCjVX1Z6oTGJWmllJmSW1C8v4vHjNNviYaKV
eBaeV6nSSL12hM90g5zaQvjHtQ6os1gauVyMjW250BmzI7Oad/ss8rOH7vEzsxC7
lhtGeuF6JawS+CRPfTA+GyxrlfRXs+KLZB7aE+P1U70qHLA59fhtGdTh/KbA+GuH
RvGOcRVrPzwro9gaVoexr+IKND9ZwFP31J9FAscynbu0Hev+NruNl3V8DgDwBU2z
6SlYE8KLqBs80dGe0kv0FKvuel/63SEmTs/Nt6tnXBwX5OzQXr2w5D4flmFpbKBJ
wpMwTWU2
=XEJx
-----END PGP SIGNATURE-----

**Comment by tuxor1337** [comment] 2017-09-28 06:52
I'm also on Firefox 55.0.3 with language de_DE and still can't reproduce the issue with PassFF 1.0.3linux.

The changes in the locale message strings is intended: see https://github.com/passff/passff/issues/223 and https://github.com/passff/passff/pull/213

**Comment by mowgli** [comment] 2017-09-28 06:57
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Am Do den 28. Sep 2017 um  7:52 schrieb Thomas Vogt:
> I'm also on Firefox 55.0.3 with language de_DE and still can't reproduce the issue with PassFF 1.0.3linux.

Strange.

> The changes in the locale message strings is intended: see https://github.com/passff/passff/issues/223 and https://github.com/passff/passff/pull/213

I cannot reporduce this two.

However, if I read correct, they are not about FF than about chromium.

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAlnMnUQACgkQpnwKsYAZ
9qygnwwAgJ4p5LtppGeRINH6pR/cN+cnudnQw/7kPVVe8o8H9wkTVbtO0xkCxa7A
ARdWQLFiGh2oqGU1l2/sPPfjM5irCjZyQJgUdOGqN7jSa/3TCh1j4NxxNQrfWQE1
TRhkfRk464rwnIVrFYiuR2mI2D064t3n9ALpQNpSOLx8417Yo14O1rrFQmn8WCpE
XBGyXyNRrY4brWww9pWG/s4qduExTbriVP7e7YxQLI32BprqR7tLKHPOQvTiv++j
OQcWwYdAk5k7zV+llIjyl5SwZy9vHq1OJfyap3NXrq62YdXBY/PwwGBD2N8lGQOz
I1dykGdtx1oAo6dubqmX6hccZC/GRtv+LhChS+i3MuWuxT8y0nTN1ZfeRjFpR/Uz
yiMTKoCMWlHWOTkFYn5lNiWsB6W7y3jn0mCamBSegd8KI3tqtkWP8gQ80L6YMT9D
si0ixWqWUTkUEXg2ILMX+5OBjCIScGEOzayLt7JkOtWN13ItF8YvgNV9NTmQ2c/O
i+D1REcz
=6XYl
-----END PGP SIGNATURE-----

**Comment by mowgli** [comment] 2017-09-28 07:02
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hmm.. That is strange, after a install of version 1.0.1 and then back to
1.0.3 it seems to work.

Maybe the version on addons.mozilla.org was broken two days ago.

You might close the issue.

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAlnMnpoACgkQpnwKsYAZ
9qyaLgwAjB/1WCt1LT/zT+yfgrZvGhDIYHnywkazwc/f2WuQO81QG7ZL5l7rGNTb
Uy0yR/vm4yWt84LecCGhFb3UfdT+49SGO26tzHrxSvVvxX6MN+kj7NSNvIy4AoJZ
fnG4d9kR56B7ZECMCgZf6dsnDD9oxi/M9zb4C01HqsizADs8TZanFZSRa5K8ryda
+rrg/Mo0PBZYWlxEfbkNiZd/Kch2OCkfs7/94KAVrhuIEdrp2Ku3DxOLUWa07m0y
w1nAqZPPhB3p/J93d4PHXltMNXInkzXyP27zQ8hgZ08Wwoid5FEUChNkR6Vf2feF
hHqlx5k+XK8hgbTj2Ob+JXcvmaJEcJ4Ph0IjZOJJQPgUL+zxbGlPHY3TjwnEy3wl
fl8XHp9ea43KcoATiFYd0tPem+ZADyHyd5QP1gaXx+Z5ZokpF4eEF7E/xm8mqPoi
ewWipkHN06fW/GlBGwGEA3wX7AJhItw8Fnrhj8USJiqeIfCNOW+kD+ZT/5fc7L+u
NwO3sMyA
=84hR
-----END PGP SIGNATURE-----

**Comment by mowgli** [comment] 2017-09-28 08:16
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I was able to reproduce the bug.

As the addons.mozilla.org website is a pain in the a..., I usually use
ansible (alzadude.firefox-addon) to install addons from the URL
https://addons.mozilla.org/de/firefox/addon/passff/.

When I install the version 1.0.3 once via webpage (after several pains
with the cross-scripting javascript crap) I can install it afterwards
via ansible again.

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAlnMr+kACgkQpnwKsYAZ
9qwvvgwAoJDIXj4KZ/qaAIrEaVQoSn1ms0LJxhIrszNbjh0O0YCC4IBOflHEk3Xo
ByTrdqnAaFMdy4g1pu5Cs/hRmULPYP7/skgWn9oKLHHbBlExHLOVw6LEF9LHrTgq
uxDtaLY+M2gXhXuQ7Ama7qIK/SAZ1xU1Ij2xCBWu9eMWSjxw3xYYfm3wFaWCgg+b
/v2/WO4x6N7/kg+z2z/iMGfYqvn0ka6cOLwt/z3oWL2YFH/7F8H1CGaZi8pusyvu
cZBo2VPaczXw8B2BDmM5xY1HJOJVddfcDRyimHBq+MU5dOoq6V83rB658RFPpt83
CmzhWoOkAjXv5+N2QowFAR35WLG9ysU2RrhilzJCFhlOh2e9Xs5kenGk6YLSHbAZ
8d2sjuMY+V2rgHkROoF+OwWtSo3cQbebZnxdf+w1P7TWcyGCm45PdvMBxpkVnK4d
nzaVJxcoj25RUkDUbJKoee/O3hrQMUNpdcqq1rTzHug60IpbT72DQUc15XHbVyvH
wDqdQis1
=2Dmf
-----END PGP SIGNATURE-----

**Comment by tuxor1337** [comment] 2017-09-28 12:41
So, this seems to be related to an outdated version of PassFF. Closing this...

**Closed by tuxor1337** 2017-09-28 12:41 UTC

**Comment by mowgli** [comment] 2017-09-28 13:15
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi Thomas,

Am Do den 28. Sep 2017 um 13:41 schrieb Thomas Vogt:
> So, this seems to be related to an outdated version of PassFF. Closing this...

Not really. It is about how to install passff. If you install (or
update) it using the FF way via addons.mozilla.com, it seems to work.
But if you install it by copying the same files via filesystem to the
same location, FF seems to ignore the new language files.

I do not know if that is a bug in FF or has to do something with the
way, passff is using it.

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAlnM9ccACgkQpnwKsYAZ
9qwexQv+KnzjmpFpmm7P4BJcuN1er9TFdryqQZfSvOtgLSyXYiSChKlixuEsNTnB
a2umgWILWXilksddpxtUslVeX1MmzfPBXUNbQwQl/BeDvcVU1ntyLgOMoNuMRCCr
RdhUV90I5yVcNQqQlAC+K0vv3X/WZrJldD5NtDgojJMtc1jMsnlyzghRN1tvI1rb
/Wpyu+/sxc7Q2kq7dHQLSSVU+P9oXGoE/h9PRGsD/DDjYLHibbBqotFBDl98ih9a
tWjme1DnwkqKNlPECCQtd35hWLGWzTRwFQCGI/RuxKCj4m86SUsKLNCcSRkGvF+3
X1r58O1C0av77wfBqaG/I6Ghort3JnNyduNMxdx/Bo0aaOH34ogJs7Z84qbfmPG9
S6rVM16SyKYZFsi77O4lXwve768xoBL1BWh/TjsjpVB17JCbPiBadOHk6jprK9Rc
BwIw3WXIUCaZZ2T9v5MQhZdd/cpJgA3+cxRV+LeH8X+uIyuyLRVMN7CPCC7T2wtf
Z2JWiCvz
=MKs5
-----END PGP SIGNATURE-----
