### ISSUE TITLE
URL matching is broken for me after v1-pre-release-22

### ISSUE THREAD

**Issue by tampakrap** [passff/passff#91] opened 2015-07-02 11:21 UTC
After v1-pre-release-22, there are some improvements for the URL matching, that actually broke my workflow. I do understand that having a URL matching pattern that suits everybody is not possible, but I'd like to offer my feedback either way :)

I keep passwords under .password-store/sites, which is the directory that passff is reading. It consists of:
- accounts for a specific website, eg: .password-store/sites/subdomain.example.com.gpg
- LDAP accounts, eg: .password-store/sites/example.com.gpg
- alternative accounts, eg: .password-store/sites/alt/subdomain.example.com-admin.gpg

Until v1-pre-release-21, passff was showing as first option:
1) full domain if it matches, eg when I visit subdomain.example.com then subdomain.example.com.gpg was first
2) only the base domain if the subdomain didn't match, eg when I visit ldap.example.com, it would match example.com.gpg

After v1-pre-release-22, passff is showing as first option any subdomain, even if there is no full match. I'm not really sure how it tries to match the URL, but the above workflow is now broken

**Comment by countsudoku** [comment] 2015-10-14 20:26
+1

It's even worse. If you use a directory _www_ instead of _sites_ it will match always to the first entry in this directory.

**Comment by nwallace** [comment] 2017-05-31 18:45
I'm working on replacing the URL-matching algorithm with an external library that should be much more accurate. More details here: https://github.com/passff/passff/issues/78#issuecomment-305270389

The proposed solution would address this problem. If you have any other thoughts or feedback, let's take the discussion over there.

Closing as duplicate of #78

**Closed by nwallace** 2017-05-31 18:45 UTC
Labels: enhancement
