### ISSUE TITLE
Unable to access passwords after removing and reconnecting a Yubikey

### ISSUE THREAD

**Issue by jamesscottbrown** [passff/passff#366] opened 2018-09-26 14:33 UTC
I use ``pass`` together with a Yubikey, which acts as a smartcard storing my GPG key. If I temporarily leave my computer, and remove the Yubikey, then ``passff`` is (as expected) unable to decrypt passwords; ``passff`` displays the message:

     [20:48:18] ls -> (2) gpg: decryption failed: No secret key

However, when I re-connect the Yubikey, then passff (contrary to my expectation) remains unable to perform decryption. I would like to be able to access stored passwords without having to restart Firefox.

Is there a way to restart passff without restarting Firefox?

**Comment by jamesscottbrown** [comment] 2018-09-26 15:39
I don't think it is a ``gpg-agent`` problem in my case:

1. after reconnecting I can run ``pass`` at the command line (or do a ``git push``/``pull`` using SSH authentication backed by ``gpg-agent``) without any problems, and without needing to restart anything

2. restarting ``scdaemon`` and ``gpg-agent`` doesn't fix `passff`` for me

(At least on Ubuntu; on MacOS I do have to kill and restart gpg-agent reasonably often)

**Comment by 5bentz** [comment] 2018-10-12 20:41
> Is there a way to restart passff without restarting Firefox?
In `about:addons`, you can disable and re-enable PassFF. That may do the trick.

Could it be a kind of *"pinentry-issue"*? (quotes and italic to emphasize it is probably not literally a pinentry issue). https://github.com/passff/passff#passff-does-not-prompt-me-for-the-passphrase

You may follow the [advanced troubleshooting guide](https://github.com/passff/passff-host#advanced-troubleshooting) to try to pin down the cause.

**Comment by shtrom** [comment] 2019-07-04 01:11
From experience, it could definitely be a pinentry issue.

Does `pass <whatever password>` in a term after the replug or after the kill:
1. prompt for a passphrase
2. fixes the passff issue?

In addition, instead of killing everything, maybe killing the scdaemon would be enough (in which case, firefox and passff would not lose their handle to the gpg-agent):
```gpg-connect-agent 'scd killscd'```

**Comment by ktolbol** [comment] 2021-05-21 18:15
I had this exact problem, and can confirm that `pass <whatever password>` indeed prompts for pinentry, after which passff works beautifully again. I followed the instructions 5bentz linked to, and can confirm that a graphical pinenetry resolves this issue: passff now correctly prompts for a pin after the yubikey has been reinserted, and all is well! Thanks a lot for the help, and for an excellent piece of software!

**Comment by tuxor1337** [comment] 2024-05-22 15:03
Closing as fixed.

**Closed by tuxor1337** 2024-05-22 15:03 UTC
Labels: bug
