### ISSUE TITLE
No entries listed in PassFF, while CLI and Emacs show / list entries as expected.

### ISSUE THREAD

**Issue by jasonm23** [passff/passff#516] opened 2022-09-19 06:25 UTC
### Versions
- Operating system: Macos Big Sur
- Browser: Firefox 104.0.2 (64bit)
- PassFF: 1.14
- Host app: `VERSION = "1.2.3"`

Status line output: `[12:37:59] ls -> (0) no error message`

(Time in now 13:19)

### Observations

- Output of `pass`: works ok, grep, show, ls etc. as expected.
- Your preferences
  - In PassFF: Nothing listed/no search results, Toplevel blank.
  - In the host app `passff.py`: 
   
        echo -e "\x02\x00\x00\x00[]" | /path/to/passff.py | tail -c +4; echo
        {"exitCode": 0, "stdout": "?,L4c_6Bk15wNH{2\n", "stderr": "", "version": "1.2.3"}
- Messages in the web console: 

```
[PassFF.content] Refresh request received in content [util.js:84:14](moz-extension://c6f16346-20e1-47c5-95ba-826956422f89/modules/util.js)
[PassFF.content] 0 matches for https://github.com/passff/passff/issues/325 [util.js:84:14](moz-extension://c6f16346-20e1-47c5-95ba-826956422f89/modules/util.js)
```

---

### Steps to reproduce the issue
1. Start FF
2. Visit any site
3. Open passff tool window.

### Actual behaviour

No results shown.

### Expected behaviour

Should see pass entries.

### Side notes

In terminal and Emacs, I can view all pass entries as expected.

I re-installed  the PassFF extension and passff.py command line tool a couple of times today.  Second time around I deleted the passff items in the FF native messaging folder.

**Comment by jasonm23** [comment] 2022-09-19 07:09
I had added an entry at `/.` which pass didn't seem to mind, but was  discovered when I ran `pass` without any args.

**Comment by jasonm23** [comment] 2022-09-19 07:11
Reopening as it's root cause was that passff added the `./` entry.

**Comment by tuxor1337** [comment] 2022-09-19 16:26
Closing as duplicate of #429

**Closed by tuxor1337** 2022-09-19 16:26 UTC
