### ISSUE TITLE
Passff stopped working

### ISSUE THREAD

**Issue by delijati** [passff/passff#425] opened 2019-11-25 17:21 UTC
### General information. Describe your environment

- Versions
  - Operating system: Ubuntu 18.04
  - Browser: Firefox 70.0.1
  - PassFF: 1.9
  - Host app: newest VERSION=1.2.1
  - `% pass --version v1.7.1`

Status line output: `[hh:mm:ss] show -> (0)`
[18:16:12] ls -> (-1) PassFF failed to execute the host app

---

### Actual behaviour
Not working at all

### Expected behaviour
Working ;)

**Comment by tuxor1337** [comment] 2019-11-25 18:27
Why are you using the outdated version 1.7.1 of PassFF?

**Comment by subins2000** [comment] 2019-11-26 15:35
@delijati Can confirm. It doesn't work for me with PassFF 1.9. It stopped working after Firefox update.

**Comment by tuxor1337** [comment] 2019-11-26 22:45
I can't reproduce with PassFF 1.9.1 and Firefox 70.0.1 on Fedora.

**Comment by subins2000** [comment] 2019-11-29 08:28
I did a [Firefox refresh](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings), installed the extension and it worked.

This seems to be an [issue with Firefox upgrade](https://support.mozilla.org/bm/questions/1271814).

**Comment by tuxor1337** [comment] 2019-11-29 08:37
Can you confirm this @delijati ?

**Comment by delijati** [comment] 2019-12-01 11:32
updated version ...

**Comment by tuxor1337** [comment] 2019-12-01 18:47
@delijati I mean, can you reproduce your issue after a Firefox refresh as proposed by @subins2000?

**Comment by tuxor1337** [comment] 2019-12-01 18:49
@delijati I mean, can you reproduce your issue after a Firefox refresh as proposed by @subins2000?

**Comment by MeisterP** [comment] 2019-12-03 10:08
Same issue here after updating to firefox-71.0. A profile refresh did not help.

**Comment by delijati** [comment] 2019-12-03 19:33
@tuxor1337 i did a refresh and now i'm stuck with `[20:23:56] ls -> (-1) PassFF failed to execute the host app` i reinstalled everything and in the console everything works.

**Comment by nbrondeau** [comment] 2019-12-05 10:59
I confirm, no longer works since the last update  71.0-1 debian sid

**Comment by nning** [comment] 2019-12-05 14:51
Profile refresh also did not work for me.

**Comment by delijati** [comment] 2019-12-08 11:58
@tuxor1337 it is working again for me ... 

the password folder `password-store` was recursively copied withing the tree. after removing all the copies it worked again. I'm not sure if this is an error of `passff` of of my synctool (seafile).
```
.password-store
...
--> password-store
      ...
----> password-store
        ...
```

**Comment by tuxor1337** [comment] 2019-12-08 12:48
Thanks for your feedback! PassFF does never do direct filesystem manipulation, but it only interacts with the command line `pass` command. That's why I don't think that the recursively copied directories have been caused by PassFF.

**Comment by tuxor1337** [comment] 2019-12-08 12:49
I'm closing this. Please refer to #427 for problems with Firefox 71.

**Closed by tuxor1337** 2019-12-08 12:49 UTC
Labels: unconfirmed
