### ISSUE TITLE
OSX: passff 1.2 not displaying any passwords

### ISSUE THREAD

**Issue by jarhill0** [passff/passff#310] opened 2018-03-25 20:40 UTC
Firefox 59.0.1 (64-bit), macOS.

I was having an issue where passff displayed an error message about getting an unexpected reply from the host app. Then I edited the preferences section of `~/Library/Application\ Support/Mozilla/NativeMessagingHosts/passff.py` so that `command = "/usr/local/bin/pass"` instead of `"/usr/bin/pass"`. Now I no longer have the issue where I get an error message; instead, I get a blank list of passwords. My host version is 1.0.1. 

My preferences:

```
################################################################################
######################## Begin preferences section #############################
################################################################################
command = "/usr/local/bin/pass"
commandArgs = []
commandEnv  = {
    "TREE_CHARSET": "ISO-8859-1",
    "PATH": "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
}
charset     = "UTF-8"
################################################################################
######################### End preferences section ##############################
################################################################################

```

I edited these to uncomment the `PATH` and `command` that were labelled as defaults for macOS.

**Comment by tuxor1337** [comment] 2018-03-25 20:53
Unfortunately, there is no way I could test this myself on Mac without a mac machine. It would be great though if you could provide us with the debugging output from `about:debuggin` following the instructions from here: https://github.com/passff/passff/blob/master/docs/CONTRIBUTING.md#development

**Comment by jarhill0** [comment] 2018-03-25 20:59
Installing the latest version of the host (passff/passff-host@1feab77c59bab91451242dba0fa3f1e6cf95e8f9) fixes this issue for me.

**Comment by tuxor1337** [comment] 2018-03-25 21:58
Ah, okay. Then I'm closing this as a duplicate of #266 and #290. Thanks for testing!

**Closed by tuxor1337** 2018-03-25 21:58 UTC
Labels: duplicate, incompatibility

**Comment by jarhill0** [comment] 2018-03-25 23:08
I have closed and re-opened Firefox and I'm back to square one. Nothing about my configuration has changed, but now I get



> Connection to the host app failed or returned an unexpected result!
> 
> Make sure you have the latest version of the PassFF host app installed by following the installation instructions on GitHub.

**Comment by jarhill0** [comment] 2018-03-26 05:09
@tuxor1337 I cloned the repo locally and loaded it in `about:debugging`. Then, I enabled add-on debugging in `about:debugging`. I didn't enable debugging in passff preferences. Then, I clicked "debug" below passff in `about:debugging`. I opened passff to see the error message.

In the console tab of the debugger, the following was printed (sorry for the poor formatting):

```
Error: WebExtension context not found!  ExtensionParent.jsm:855:13
error occurred while processing 'sources: TypeError: can't access dead object
Stack: createNonSourceMappedActor@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/TabSources.js:313:1
createSourceActors/<@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/TabSources.js:401:19
process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:922:23
walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:806:7
scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:742:11
Line: 313, column: 1
```

**Comment by tuxor1337** [comment] 2018-03-26 06:10
Hm, these logs seem entirely unrelated to PassFF. Did you enable debug output in the PassFF preferences? Do this, then open the debug console and after that do a reload of the extension in the `about:debugging` interface.

**Comment by jarhill0** [comment] 2018-03-26 14:46
My mistake. I'm pretty clueless about WebExtension debugging. 

I followed what you said and:

```
[PassFF] Message Pass.loadItems received in background  util.js:36:9
[PassFF] The host app is outdated! _VERSIONHOLDER_  util.js:36:9
[PassFF] loadItems failed!  util.js:36:9
[PassFF] Init auth module  util.js:36:9
[PassFF] Awaiting tab init... 3 about:debugging  util.js:36:9
[PassFF] Tab init done 3 about:debugging  util.js:36:9
[PassFF] Awaiting tab init... 3 about:debugging  util.js:36:9
[PassFF] Tab init done 3 about:debugging  util.js:36:9
[PassFF] Awaiting tab init... 3 about:debugging  util.js:36:9
[PassFF] 0 matches for about:debugging  util.js:36:9
[PassFF] Tab init done 3 about:debugging  util.js:36:9
[PassFF] Message Pass.loadItems received in background  util.js:36:9
[PassFF] Message Menu.getLastState received in background  util.js:36:9
[PassFF] Create menu list Array [  ]  util.js:36:9
[PassFF] Create children menu list Array [  ] true  util.js:36:9
[PassFF] Awaiting tab init... 3 about:debugging  util.js:36:9
[PassFF] Tab init done 3 about:debugging  util.js:36:9
```

That's what was printed to the debug console when I loaded the extension and got the error message about an unexpected result.

**Comment by jarhill0** [comment] 2018-03-26 14:51
I notice in the logs that PassFF is complaining about the version of the host application, which is not `1.0.1` because I installed from the latest git commit. I manually edited the `.py` file so that the version is `1.0.1` and repeated the debug process. Passff no longer complains about the version of the host, but doesn't display any passwords. Here is the log output:

```
[PassFF] Message Pass.loadItems received in background  util.js:36:9
[PassFF] Message Pass.loadItems received in background  util.js:36:9
[PassFF] Message Menu.getLastState received in background  util.js:36:9
[PassFF] Create menu list null  util.js:36:9
[PassFF] Create contextual menu  util.js:36:9
[PassFF] Create menu list Array [  ]  util.js:36:9
[PassFF] Create children menu list Array [  ] true  util.js:36:9
[PassFF] Message Menu.backupState received in background  util.js:36:9
[PassFF] Script execution ok  util.js:36:9
[PassFF] Init auth module  util.js:36:9
[PassFF] Awaiting tab init... 3 about:debugging  util.js:36:9
[PassFF] Tab init done 3 about:debugging  util.js:36:9
[PassFF] Awaiting tab init... 3 about:debugging  util.js:36:9
[PassFF] 0 matches for about:debugging  util.js:36:9
[PassFF] Tab init done 3 about:debugging  util.js:36:9
[PassFF] Root button command  util.js:36:9
[PassFF] Create menu list Array [  ]  util.js:36:9
[PassFF] Create children menu list Array [  ] true  util.js:36:9
[PassFF] Root button command  util.js:36:9
[PassFF] Create menu list Array [  ]  util.js:36:9
[PassFF] Create children menu list Array [  ] true  util.js:36:9
[PassFF] Context button command  util.js:36:9
[PassFF] Create contextual menu  util.js:36:9
[PassFF] Create menu list Array [  ]  util.js:36:9
[PassFF] Create children menu list Array [  ] true  util.js:36:9
[PassFF] Message Menu.backupState received in background  util.js:36:9
[PassFF] Root button command  util.js:36:9
[PassFF] Create menu list Array [  ]  util.js:36:9
[PassFF] Create children menu list Array [  ] true  util.js:36:9
[PassFF] Context button command  util.js:36:9
[PassFF] Create contextual menu  util.js:36:9
[PassFF] Create menu list Array [  ]  util.js:36:9
[PassFF] Create children menu list Array [  ] true  util.js:36:9
[PassFF] Message Menu.backupState received in background  util.js:36:9
[PassFF] Refresh button command  util.js:36:9
TypeError: el.parentNode is not a function[Learn More]  menu.js:183:41
[PassFF] Refresh button command  util.js:36:9
TypeError: el.parentNode is not a function[Learn More]  menu.js:183:41
[PassFF] Root button command  util.js:36:9
[PassFF] Create menu list Array [  ]  util.js:36:9
[PassFF] Create children menu list Array [  ] true  util.js:36:9
[PassFF] Context button command  util.js:36:9
[PassFF] Create contextual menu  util.js:36:9
[PassFF] Create menu list Array [  ]  util.js:36:9
[PassFF] Create children menu list Array [  ] true  util.js:36:9
[PassFF] Message Menu.backupState received in background  util.js:36:9
[PassFF] Awaiting tab init... 3 about:debugging  util.js:36:9
[PassFF] Tab init done 3 about:debugging  util.js:36:9
```

**Comment by tuxor1337** [comment] 2018-03-26 17:46
Ah, very helpful!! Using your logs I found a bug in https://github.com/passff/passff/blob/master/src/modules/menu.js#L183 - however, I doubt that this fixes your issue... :-/

By the way, when using the latest host app from GitHub, please follow the installation instructions given here: https://github.com/passff/passff-host#latest-from-github

**Comment by jarhill0** [comment] 2018-03-26 19:09
Just tried again with the host installed as described in the README (version is "testing"). Initially, I got the "unexpected response" error, but once I uncommented the macOS defaults, I no longer got that error. Everything currently works as expected, but I think that might change if I quit and re-open Firefox.

**Comment by jarhill0** [comment] 2018-03-26 19:11
Works after restart, even for the signed version.

**Comment by tuxor1337** [comment] 2018-03-26 19:17
Strange ... But glad to hear that it works for you now :+1:
