### ISSUE TITLE
install of py app fails

### ISSUE THREAD

**Issue by sp2004c** [passff/passff#303] opened 2018-03-08 14:51 UTC
py file gets truncated to 2 bytes

path in JSON is wrong

one must do it all manually

**Comment by tuxor1337** [comment] 2018-03-08 14:55
Would you please give step by step instructions on how to reproduce your issue.

Furthermore, I don't seem to understand what's the problem. Which py file are you talking about and how and when it is truncated?

**Comment by tuxor1337** [comment] 2018-03-15 13:04
Closing this due to a lack of information. Reopen with requested info if you wish.

**Closed by tuxor1337** 2018-03-15 13:04 UTC
Labels: invalid
