### ISSUE TITLE
FF ESR: Context button defect

### ISSUE THREAD

**Issue by mddvul22** [passff/passff#272] opened 2018-01-10 12:10 UTC
I'm using version 1.1.  The option for "Mark fillable input fields with icon" is working great for me.  However, I have another computer that I share with another person.  On that computer, I uncheck that box in the addon preferences.  For that computer, I rely completely on the addon icon in my toolbar menu.

I've noticed, since the update, to 1.1 that passff isn't prompting me for possible url matches, in the toolbar button.  It shows options (fill, fill and submit, etc.) for the pass entry that I previously used.  This results in me using sending incorrect credentials to the current site that I'm trying to login to.

To fix, I then have to click on display root, then scroll to the appropriate entry and work my way back in.  Also, I  don't know if this is related, or not, but I have also noticed that "display contextual" isn't working in the toolbar button (again, works fine for me, if I'm marking input fields).

**Comment by tuxor1337** [comment] 2018-01-10 12:20
I cannot reproduce this on Firefox 57.0.4 on Linux. Which version of Firefox and which operating system do you use?

**Comment by mddvul22** [comment] 2018-01-10 13:33
I can replicate this on two computers.  Both running Firefox ESR 52.5.x.  One is Debian 9, the other is MacOS 10.12.6 (Sierra).

**Comment by tuxor1337** [comment] 2018-01-10 14:45
Okay, I can confirm that this is an incompatibility with Firefox 52.

**Comment by 5bentz** [comment] 2018-01-12 23:11
(I use PassFF on Firefox 52 ESR and Debian Stretch).
Oh so that's a bug?!
Yeah I can confirm passff has been a bit silly for a while now. It's no big deal to me.

By comparing to Firefox Dev Edition (v.58), I observe that:
* Button 'Display contextual' is not working.
* Actually, passff does not display any contextual password when clicking on the menu icon
* It systematically sticks to the last password used, whatever the option ("goto...", "fill...", "copy...", "display") whereas ff58 has different behaviours depending on the option.
* It keeps the last search.

By testing, I found other silly behaviours.

Bug? in BOTH version
* It keeps my aborted searches: type 'ABCD', then close the menu (by clicking elsewhere).

Actually it is better than that (BUG? in both versions ;)
* If you remove a word (using Backspace key, one character at a time), it even keeps the first character of the word (or the last character deleted): type 'ABCD' then delete it. Close and reopen the menu: wouaw: 'A'! (But it does not actually search anything. No matching passwords are displayed)
* If you remove a word holding Backspace key, it is brought back: type 'ABCD' then delete it by holding 'Backspace' pressed. Close and reopen the menu...'ABCD'!
* Wait, if you delete some characters with the 'Del' key, PassFF brings them back! Type 'ABCD' then delete 'BC' or 'ABC' or the whole string. Close the menu, reopen it...'ABCD' is back! MAGIC!  

In FF 58, I can clear the search bar by going to another tab (I can go back & forth for example). Strange?.  

(Meanwhile, on my Debian Stretch believed 'stable')
OMG MY X WINDOWS SYSTEM IS BROKEN OR WHAT? I'm now currently connected to my computer with x11vnc/ssvnc. C'mon. Does anyone know how I can troubleshoot this (other) issue. I(n)ssue-ception :d

**Comment by tuxor1337** [comment] 2018-01-12 23:34
Y'know, from my point of view, it's not a bug. I'm currently the most active developer here and I'm using Firefox 57, so I'm targeting for this version of Firefox only. If somebody comes up with issues that only apply to Firefox ESR, then it's an incompatibility - not a bug.

For the behaviour of the search bar: That's not a bug, it's a feature. It just fits my usecase. It does exactly what I expect the search bar to behave like. If you feel like this should change, open a new issue explaining your thoughts. It will be tagged as an "enhancement" and maybe I will try to help you, maybe not. If I don't have the time to implement your request, feel free to open a pull request with your own implementation. That's how it goes ;-)

**Comment by 5bentz** [comment] 2018-01-13 02:26
I agree with your point of view.
The root problem is Mozilla dropping support for XUL extensions, not PassFF having to comply with old software. Besides, the *bug* is quite minor. I don't even bother about it.

For the behaviour of the search, may I create an issue for documenting this feature? Or is there another way of documenting it?

Indeed, this is relevant to the old title of this issue.

**Comment by tuxor1337** [comment] 2018-03-25 20:14
While doing some testing with ESR for #309, I found an error which is at first sight unrelated to this. But since I fixed it, the context button works. Therefore, I'm closing this. If you still experience this issue with the latest code from Github, feel free to reopen with a description of your setup.

**Closed by tuxor1337** 2018-03-25 20:14 UTC
Labels: incompatibility

**Comment by 5bentz** [comment] 2018-03-25 23:45
# Setup

Mozilla Firefox 52.7.2
Pass v1.6.5
Debian GNU/Linux 9 (stretch)
Linux 4.14.0-0.bpo.2-amd64 (backport)


# With the old host program

...I cannot reproduce. PassFF 1.1 just works and PassFF 1.2 just fails with the error 'please check your host app'.

# Let's try with the new host program: 1.0.1.

What works:
Install 1.2 from AMO with my current profile
Install 1.2 from AMO with a new profile
Latest version from github

What does not work:
PassFF 1.1 with my current profile.

# Conclusion: I cannot reproduce the issue.

@dsommers
Are you sure the host app is correctly installed? Please could you doublecheck the path in `passff.json`.
I would try PassFF in a clean Firefox profile.
With `firefox -P`, you can easily create a second clean profile for testing and switch between profiles.

**Comment by tuxor1337** [comment] 2018-03-26 06:28
Thanks for the confirmation. Here's my explanation of what this bug was about in the words of the op:

> (...) passff isn't prompting me for possible url matches, in the toolbar button. I (...) have to click on display root, then scroll to the appropriate entry and work my way back in. (...) "display contextual" isn't working in the toolbar button

By "isn't working" we mean that the UI would show a blank list when clicking on "display contextual". However, I don't have an explanation for why 586ed4a fixes this.

**Comment by 5bentz** [comment] 2018-03-26 15:51
#### Running PassFF 1.2 in Firefox ESR prints
```
[PassFF] Script execution ok  util.js:36:9
[PassFF] Init auth module  util.js:36:9
TypeError: browser.webRequest.onAuthRequired is undefined[Learn More]  auth.js:98:7
[PassFF] Message Pass.loadItems received in background  util.js:36:9
```
I tried to disable "HTTP Authentication" in the pref: same message.

#### I investigated a bit (you can skip to the conclusion! :)

First, `browser.webRequest.onAuthRequired` has been *added in Firefox 54*, thus the error in FF ESR.
Second, `PassFF.Auth` is called by theses files:
```
~/git/passff/src (git)-[tags/1.2] % grep -Rn 'PassFF.Auth' modules
modules/main.js:161:          PassFF.Auth.init();
modules/preferences.js:131:   PassFF.Auth.init();
modules/menu.js:470:          PassFF.Auth.resolve(item);
```
preferences & menu are not interesting.

Let's see `main.js:161`
```
              PassFF.Auth.init();
              browser.contextMenus.onClicked.addListener(onContextMenuClick);
              browser.tabs.onUpdated.addListener(onTabUpdated);
              browser.tabs.onActivated.addListener(onTabActivated);
              browser.windows.onFocusChanged.addListener(onWindowFocus);
              return onTabActivated();
              break;
```

#### Observation

Several listeners are added *after* the `Auth.init()`. If the initialisation fails, then these listeners aren't added. Especially, onTabUpdated & onTabActivated: they call `loadContextItems`.

#### Testing: are the listeners added?

In FF 60, if I add a debug message in `onTabUpdated` (it lacks a debug message) with a conditional breakpoint, I'll get `[PassFF] onTabUpdated` if I click on the menu icon or if I click on "Display contextual" in the menu.
In FF ESR, I don't get this message. The listener is not called.

#### Testing PassFF.Auth (just to be sure)
I can test the initialisation of `PassFF.Auth` by adding debug messages before & after it:
With breakpoints (~ buggy)
```
[PassFF] Script execution ok  util.js:36:9
[PassFF] Before Auth init!  util.js:36:9
[PassFF] Init auth module  util.js:36:9
# No "After Auth init!"
[PassFF] Message Pass.loadItems received in background  util.js:36:9
TypeError: browser.webRequest.onAuthRequired is undefined[Learn More]  auth.js:98:7
```
By editing the code directly:
```
case "background":
  console.debug("Before auth init");
  PassFF.Auth.init();
  console.debug("Past auth init");
  browser.contextMenus.onClicked.addListener(onContextMenuClick);
  browser.tabs.onUpdated.addListener(onTabUpdated);
  browser.tabs.onActivated.addListener(onTabActivated);
```

##### Result
```
[PassFF] Script execution ok  util.js:36:9
[PassFF] Before auth init  util.js:36:9
[PassFF] Init auth module  util.js:36:9
TypeError: browser.webRequest.onAuthRequired is undefined[Learn More]  auth.js:98:7
# No "After auth init"!
[PassFF] Message Pass.loadItems received in background
```
#### Conclusion
Auth.init() does not return, thus the lines after are not executed. In particular, the listeners seems necessary to get the URL of the current tab & to match it against items (passwords).

(I confirm that FF ESR is going crazy: 100+% CPU.)

**Comment by tuxor1337** [comment] 2018-03-26 17:23
Thanks for the analysis, very interesting :+1:
