### ISSUE TITLE
Firefox hangs when GPG fails to produce a password

### ISSUE THREAD

**Issue by shtrom** [passff/passff#243] opened 2017-11-08 21:24 UTC
When GPG or the agent is in such a state that it will output the following when trying to decrypt,

    gpg: public key decryption failed: General error
    gpg: decryption failed: No secret key

PassFF makes Firefox hang forever, and the only solution is to kill it, at which point it outputs the following to STDERR before dying.

    [GFX1-]: Receive IPC close with reason=AbnormalShutdown
    [Child 11678, Chrome_ChildThread] WARNING: pipe error (3): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
    Killed

Save for the interesting reference to Chromium, it seems like it's hanging on an IPC, which I suspect would be with the PassFF helper, which itself is waiting for a decrypted stream that is not coming.

A timeout of some sort, or inspection of the return status from GPG in the helper might, well, help.

Is there a quick way I could run the helper manually (i.e., not through Firefox) to request a password decryption, so I can investigate further? Essentially, what command should I write into it?

**Comment by tuxor1337** [comment] 2017-11-08 22:04
By helper you mean the host application, right? Here, somebody modified it to log some debugging info to a local file: https://github.com/passff/passff/issues/219#issuecomment-340259566 Maybe this helps you at tracing down your issue?

**Comment by drmoose** [comment] 2017-11-19 17:30
This seems to be caused by [this infinite loop](https://github.com/passff/passff/blob/ae039624f6b136c8e6da643073952179e06042a3/src/modules/pass.js#L138).

**Comment by tuxor1337** [comment] 2017-11-20 09:05
Closed by #248

**Closed by tuxor1337** 2017-11-20 09:05 UTC
Labels: bug
