### ISSUE TITLE
Migrate to WebExtensions

### ISSUE THREAD

**Issue by emersion** [passff/passff#169] opened 2016-10-22 19:01 UTC
See https://developer.mozilla.org/en-US/Add-ons/WebExtensions

**Comment by jvenant** [comment] 2016-10-24 07:05
ouch ! Small ticket, but it involve to redesign almost everything.
I already check a little bit webextensions.
My main concern is about executing external program. It seems to require a much more complex install process.

**Comment by emersion** [comment] 2016-10-24 07:11
Yes, this involves rewriting a lot of code, but the WebExtension version would be compatible with all major browsers (Firefox, Chrome, Opera, Edge).

I see two ways of doing it:
* Using native messaging: https://developer.chrome.com/extensions/nativeMessaging
* Using the `fileSystem` API: https://developer.chrome.com/apps/fileSystem

**Comment by emersion** [comment] 2016-10-24 07:14
Damn, the `fileSystem` API is only for Chrome apps, it's not part of WebExtensions.

**Comment by hallabro** [comment] 2016-12-07 14:26
I would be willing to work with somebody to migrate this extenstion to WebExtensions if this is the prefered long term solution. I'm no expert my any means but I know my way around in javascript.

Currently I am in the position of the extension not working because I use e10s without the shim and would very much like to have a working extension. Manually copying from pass is no fun. ☹️

**Comment by emersion** [comment] 2016-12-07 14:34
There's one other solution : use a pure JavaScript Git implementation (e.g. https://github.com/maryrosecook/gitlet) + OpenPGP.js.

**Comment by hallabro** [comment] 2016-12-07 14:38
Well, `pass` may be used without git so I guess it is no universal solution.

What would be the reason to use git? To get a list of files to be decrypted by OpenPGP.js?

**Comment by emersion** [comment] 2016-12-07 14:42
A WebExtension has no way to interact with the filesystem - so we can't directly read the local pass database. Using the nativeMessaging API would require to install pass and another binary.

**Comment by hallabro** [comment] 2016-12-07 14:55
One other idea on top of my head would be to have a pass daemon providing a local WebSocket which could talk to (which I think is how 1Password does).

**Comment by emersion** [comment] 2016-12-07 15:00
Either way, something else needs to ne installed. I think it's better to use nativeMessaging since there wouldn't be a deamon always running in background.

**Comment by hallabro** [comment] 2016-12-07 15:09
Yes, I think you are right in using Native Messaging, Could you please elaborate in what other binary would be required for Native Messaging? I understand that the pass binary would be required.

**Comment by emersion** [comment] 2016-12-07 15:15
To be able to connect to an external program from a WebExtension, we need:
1. To put a manifest file (for Firefox on Linux, it's in `~/.Mozilla/native-messaging-hosts/<name>.json`
2. Build a binary that parses JSON from stdin and outputs JSON to stdout.

Here are the docs: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging

I can help with the binary if you want.

**Comment by emersion** [comment] 2016-12-07 15:23
(Note: the extension's binary can either call `pass` or use the pass database directly. It would be better for the binary to do not have any dependency so it could run on many systems out of the box)

Do you want to create a new repo for this?

**Comment by hallabro** [comment] 2016-12-07 15:31
I think it would be fair to say that any user of passff also has pass installed. Please correct me if I am wrong but I by parsing pass output we would not have to bother about any (although unlikely) upstream changes (let's say the database format would be changed for some reason).

The upside of not using the pass binary would be less dependencies, as you say.

@nwallace do you have any suggestions or ideas the future of passff (seeting as the currently used API will not be around for much longer)?

I think it would be prefered to keep as much development to this repository as possible seeing as the project already has a user base. I see forking as a last resort personally (it's also possible I misunderstood your reference to create a new repo).

**Comment by emersion** [comment] 2016-12-07 15:38
> I think it would be fair to say that any user of passff also has pass installed.

Yeah since passff calls `pass` directly. One problem with this is that `pass` can be difficult to set up on some platforms (looking at you, Windows).

> by directly calling pass we would not have to bother about any (although unlikely) upstream changes

As you say, it's very unlikely that the database format will change. This would require `pass` to bundle an upgrade script, which would be difficult to do since it's written in shell.

> I see forking as a last resort personally

I agree, but switching to WebExtension will require a full rewrite of this extension (since it's using XUL and the old Firefox extension API). So it would be a different project rather than a fork.

**Comment by emersion** [comment] 2016-12-10 18:38
Looks like someone already built a WebExtension: https://github.com/dannyvankooten/browserpass

**Comment by nwallace** [comment] 2016-12-10 18:49
Thanks for all the research and discussion. I agree, it would be great to have the plugin follow a more universal standard, like web extensions. Unfortunately, that's too far from where we are today. I'm glad Browserpass exists -- it's immature now, but with time I hope it will grow into a full-featured replacement for this extension. In the near future, though, I'm not going to be able to migrate this plugin's whole codebase to a new architecture. I'm going to focus on stabilizing the functionality we have now, and hopefully Browserpass or another plugin can address the cross-browser problem.

Any objections? Other thoughts?

**Comment by hallabro** [comment] 2016-12-10 18:55
I haven't looked into browserpass much but if it keeps on improving I would have no problems with letting it succeed passff.

**Comment by nwallace** [comment] 2016-12-11 18:35
I'm closing this issue, but feel free to re-open it if anyone has some energy around doing this yourself. Until then, this is out of scope.

**Comment by tuxor1337** [comment] 2017-02-09 22:37
I wouldn't say, this is out of scope. I started a rewrite and only minor things remain to be done: https://github.com/nwallace/passff/issues/157#issuecomment-278012810
How about reopening this?

**Comment by nwallace** [comment] 2017-02-26 19:15
Thanks a ton @tuxor1337 ! Your fork is working really well for me. I hate that Mozilla is deprecating the old addon infrastructure, but your work is awesome and I'm definitely willing to re-open this issue and get keep this extension going.

Are you aware of any other outstanding issues besides lack of support of keyboard shortcuts? If not, send over a pull request. I'm going to keep testing the branch myself in the meantime, and work on including some of the recent pull requests we've gotten on Master

**Comment by tuxor1337** [comment] 2017-02-26 19:34
I don't know of any other issues, but I have been testing with Ubuntu 16.04 and Fedora 25 only, both running GNOME. Using other operating systems or different desktop environments might be critical! Furthermore, the "Pass script" preferences section of PassFF is implemented in my fork, but I haven't really had a chance to test it (I'm using the default preferences all the time).

How do you plan to deliver the host app to users? Will you include install instructions in the extension description on addons.mozilla.org? Maybe we should think about graceful error handling if the extension runs into a missing host app. Or does firefox directly handle these situations?

**Comment by nwallace** [comment] 2017-02-26 19:40
I totally agree -- before a release we should include error handling. That was something I worked on on the addon-sdk branch, and it'll be even more important now to help people who don't have the host app installed.

For getting the host app installed, yes I think we should include some instructions on the README, in the Mozilla Addons site, and ideally in the plugin itself.  It would be awesome if when the host app isn't installed, we could show an error message with some instructions or links to instructions from the "popup" window. Right now, if you don't have the host app set up, you just don't see any of your passwords

**Comment by jabranham** [comment] 2017-03-06 07:23
Hi - 

Firefox updated and broke pass for me today. I came over here to see if there was any work moving passff to the new WebExtension framework and saw this ticket. Let me know if I can help out with testing or anything. I'm running Arch Linux if it makes a difference.

Thanks for your work on this!

**Comment by tuxor1337** [comment] 2017-03-06 09:28
Hi @jabranham !
You can definitely help testing by checking out my WebExtensions branch at https://github.com/tuxor1337/passff/tree/web_extensions and building the extension with:

    $ cd ./src
    $ make

The extension `*.xpi` file is then located in `./bin/passff.xpi`. Everything expect from the keyboard shortcut is supposed to work fine.

**Comment by tuxor1337** [comment] 2017-03-06 10:42
Oh, I'm sorry. I forgot to mention one important installation step that is not documented yet: The host app!

You should move the file in `./src/host/host.json` to `$HOME/.mozilla/native-messaging-hosts/passff.json` (create directory if it does not exist). Furthermore you would move the file `./src/host/passff.py` to some place like `$HOME/.local/bin/passff.py` mark it as executable and make note of the path in your `$HOME/.mozilla/native-messaging-hosts/passff.json` (simply replace the `PLACEHOLDER` accordingly).

**Comment by jabranham** [comment] 2017-03-06 12:30
Thanks. Seems to be working well so far. I'll let you know if I run into any issues, though!

**Comment by nwallace** [comment] 2017-03-07 01:55
@jabranham What version of Firefox are you using where it broke? I just upgraded to 52.0 and it's still working for me. I haven't heard a specific release number when they'll remove the deprecated Add-on platform, so it would be great to know if it's imminent.  I'm working on the fork by @tuxor1337 to add in some error messaging and instructions for installing the host app, but if we have to rush out a release before that's ready, we can.

Speaking of which, @tuxor1337  if you submit a pull request, I'll merge your branch into master and we can work together to prep the release

**Comment by jabranham** [comment] 2017-03-07 06:25
I think somehow e10s got enabled which was what borked it for me. 

The webextension versoin seems to be working well so far, even the keyboard shortcut (in Firefox 52+) to open the menu. It doesn't seem to be possible to select an entry using the keyboard, however. 

@nwallace - Legecy addons will no longer work in [Firefox 57](https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/). That'll hit aurora users starting in August, and eventually hit stable in November.

**Comment by guiniol** [comment] 2017-03-07 08:58
@tuxor1337 @nwallace thanks. Just tested in Firefox Developer and it works for me.
The `host.json` file has to be renamed to `passff.json` when moved to `$HOME/.mozilla/native-messaging-hosts`. I know it was in the instructions, but I want to emphasize because I just lost a few minutes wondering why it wasn't working ^^

**Comment by tuxor1337** [comment] 2017-03-07 09:02
@nwallace PR is ready.

@jabranham For me, selecting entries using the keyboard works fine (in Firefox 51). Does this work for you when clicking on the icon instead of using the keyboard shortcut to open the popup?

**Comment by jabranham** [comment] 2017-03-07 09:08
@tuxor1337 No, it doesn't. The keyboard shortcut should be Alt-1, Alt-2, etc, right?

**Comment by tuxor1337** [comment] 2017-03-07 09:09
No, keyboard navigation between the entries works using the arrow keys (up, down, left, right) and the enter key.

**Comment by jabranham** [comment] 2017-03-07 09:10
Ah, right. That doesn't work either though, either by calling it via the shortcut key or by clicking on the button.

**Comment by tuxor1337** [comment] 2017-03-07 09:37
@jabranham Okay, I tested it with Firefox 53.0a1. For some reason, there is a race condition concerning the autofocus in later versions of Firefox, but it was easy to fix it. Now your keyboard navigation should work fine (see latest commit).

**Comment by jabranham** [comment] 2017-03-07 09:40
Thanks. I just tested in Firefox 52 and they it seems to work well now. Thanks again for all your work on this!

**Comment by tuxor1337** [comment] 2017-04-08 14:29
This is almost done. Only thing missing now is the install script (and maybe some more error output).

@nwallace Have you looked into writing an install script? If not, we could simply adapt the install script from browserpass at https://github.com/dannyvankooten/browserpass/blob/master/install.sh - what do you think?

**Comment by tuxor1337** [comment] 2017-04-09 18:49
I adapted the script from `browserpass` to our situation, see commit 0128f04. Is there anything that prevents us from releasing the WebExtensions version now?

**Comment by tuxor1337** [comment] 2017-04-09 19:12
@jvenant My proposal for a shiny new screenshot for addons.mozilla.org
![passff](https://cloud.githubusercontent.com/assets/1518387/24840201/299d3620-1d69-11e7-8e8a-ea0c5761dc95.png)

**Comment by yurikhan** [comment] 2017-04-23 11:47
It looks like this version only gets the list of passwords once on startup; the reload button only re-constructs the menu. Am I reading it right?

**Comment by tuxor1337** [comment] 2017-04-23 11:56
@yurikhan No, that's incorrect. The list of passwords is retrieved on startup and every time the reload button is pressed - just as it used to be before.

**Comment by yurikhan** [comment] 2017-04-23 12:09
Indeed. My bad. I somehow got stuck with a stale list of password and the reload button would not refresh it. Restarting the browser fixed it and I can no longer reproduce the problem.

**Comment by josephholsten** [comment] 2017-05-01 18:19
@tuxor1337 @jvenant @nwallace what's remaining to cut a release here? would it be useful to move passff to a github organization so multiple people can act as administrators for this repo?

**Comment by nwallace** [comment] 2017-05-04 02:39
@josephholsten I agree -- I'll move this project to an org. @tuxor1337 has been doing an amazing job with this stuff and he deserves to have more control over the project.

As for the release, there's two things I think we still need (please correct me @tuxor1337 if you've already done either of these):

1. **Display an informative error message for anyone who doesn't have the host app installed.** I think this is vital since everyone running the current version of the add-on will encounter this error as soon as we push out the release and everyone's add-on will break.
2. **Make install_host_app.sh actually download the host app and the manifest.** As written, you have to clone the repository, cd into the /src/host directory, then execute the file. But if we make it curl down the manifest and host app, then the user only has to download the one file (which we can put on the releases page) and execute it from anywhere.

Do you all agree? Basically, I want it to be as easy as possible for everyone to upgrade their add-on.  Is there any problem with these proposals?

**Comment by yurikhan** [comment] 2017-05-04 04:28
An error message is definitely needed.

As for downloading and installing the messaging host, however: Do you really want users to run a random script from the Internet, that will download and install a random messaging host, that will allow your extension to give it access to all the user’s passwords? In other words, why should the user who installed the extension from MDN trust the script and messaging host from GitHub?

**Comment by nwallace** [comment] 2017-05-04 04:56
@yurikhan Yeah, I know it's a potential concern, but how many times have you run a curl-piped-to-sh one-liner to install something? I know I do it. Everything's open source and plain text scripts. The user could easily inspect the script before running it. If they were concerned, they could then go inspect the .json and .py files it would download as well.

That being said, I'm open to suggestions. If we think it's better to have them download the 3 files themselves, clone the Github repo, or do something else, we can do that instead.

**Comment by davidar** [comment] 2017-05-04 06:03
I imagine people who are already using pass won't have much of an issue with needing to clone a git repo, so I'd call that more of a nice-to-have rather than a release blocker.

@yurikhan presumably the MDN extension will provide the link to the script/repo, so it's not exactly just a random thing off the internet (at least no more so than the extension itself is a random thing off the internet :wink:)

**Comment by nwallace** [comment] 2017-05-04 06:10
I've opened a pull request #196 as a place where we can discuss the potential change to the host app installation script. Like I said, personally I would prefer a simple copy/paste one-liner to install the host app, but I know that's scary to some, so let's debate the issue there.

**Comment by luca-ing** [comment] 2017-05-04 07:53
> As for downloading and installing the messaging host, however: Do you really want users to run a random script from the Internet, that will download and install a random messaging host, that will allow your extension to give it access to all the user’s passwords?

@yurikhan I'm already downloading a browser extension that handles my passwords in plaintext, sight unseen. How is running the install script sight unseen any different?

(And yes, I could in theory inspect the source code, but I have neither the time nor the JS skills to do that. I have no realistic alternative but to trust you guys.)

**Comment by tuxor1337** [comment] 2017-05-05 18:43
@nwallace The error handling looks fine for me. Thanks!

I added the German translation. Unfortunately, I can't help with the Russian translation. But I'm not sure whether this really is a release blocker.

**Comment by nwallace** [comment] 2017-05-05 22:57
@horosgrisa did the Russian translation initially. Can you help us again @horosgrisa ? I can let you know which keys are missing if you need help with that. If not, I'll just throw some stuff into Google Translate to make sure nothing's missing, and then I think we're ready for a release!

**Comment by paulperegud** [comment] 2017-05-10 08:09
@nwallace I would love to help with Russian translation. Please point me in the right direction!

**Comment by josephholsten** [comment] 2017-05-10 14:52
@paulperegud спасибо!

I don't know the best workflow or tools, but ultimately we're trying to populate: [src/_locales/ru/messages.json](https://github.com/nwallace/passff/blob/master/src/_locales/ru/messages.json)

**Comment by paulperegud** [comment] 2017-05-10 18:54
@nwallace @josephholsten done in #197

**Comment by nwallace** [comment] 2017-05-28 02:08
Thanks everybody! I've submitted a new version to Mozilla. It's going through the review process now. I'm very grateful to everyone who helped out with this release, especially @tuxor1337 for doing the great bulk of the rewrite. I've moved the project to an org now and I think we're ready for the big upgrade to hit the browser. Next up: Chrome support!

**Closed by nwallace** 2017-05-28 02:08 UTC
Labels: enhancement, incompatibility

**Comment by tuxor1337** [comment] 2017-05-28 06:49
@nwallace Great, thanks! How about a new screenshot for addons.mozilla.org?

![](https://cloud.githubusercontent.com/assets/1518387/24840201/299d3620-1d69-11e7-8e8a-ea0c5761dc95.png)

**Comment by jabranham** [comment] 2017-06-11 09:34
@nwallace any idea when this will actually appear on Mozilla's addons page? https://addons.mozilla.org/en-US/firefox/addon/passff/ still shows version 0.1.32 from September 2016

**Comment by tuxor1337** [comment] 2017-06-11 10:04
Regarding add-on review queues: https://blog.mozilla.org/addons/2017/05/15/add-ons-update-95/

Since this upgrade introduces major changes, it's not surprising that this review belongs to the group "after more than 10 days" which makes up 15 percent of all reviews. Now it's been 14 days since submission, but still, I would wait at least one more week before making any efforts on what's going on.

**Comment by jabranham** [comment] 2017-06-11 11:36
Thanks! I knew there was a review process but didn't know it could take this long.

**Comment by jvenant** [comment] 2017-06-11 13:23
It took something like 6 months for me the first time...

**Comment by tuxor1337** [comment] 2017-07-26 15:40
@nwallace Would you please give feedback on the current review state? According to IRC (#addon-reviewers) you have been contacted by a reviewer.

**Comment by girst** [comment] 2017-08-19 22:14
With the fact in mind that the old version currently published on AMO is broken for FF55, it's time to get [this](https://github.com/passff/passff/issues/207) sorted out. 

I am no expert in WebExtensions, but I'd like to help out! @nwallace - do you know why AMO [rejected](https://discourse.mozilla.org/t/passff-review/18036/2) the update?
