### ISSUE TITLE
Forms that demand 'real' typing before activating login button

### ISSUE THREAD

**Issue by phipolis** [passff/passff#244] opened 2017-11-11 18:54 UTC
I'm noticing a terrible trend in the design of login forms to refuse to submit the login request until typing is registered in both the username and password fields. They do this either by keeping the login button disabled until typing happens, or by redirecting the login button to display a "Password is required" notice. Thus, PassFF's fill option will put valid credentials into the fields, but I still won't be able to login.

The workaround is usually to type an extra letter after the pass-filled username, backspace it, and then type a letter after the password and backspace it too. Then and only then will the login button work. I realize this is braindead web design and not PassFF's fault, but is there any way for it to simulate the events that these client side Javascripts want in order to believe the input has happened?

One example that comes to mind is https://www.duquesnelight.com/ -- it if you fill with PassFF and click login, it creates a red box saying "The Username field is required The Password field is required". I'll be looking for more examples.

**Comment by tuxor1337** [comment] 2017-11-19 18:23
Duplicate of #182

**Closed by tuxor1337** 2017-11-19 18:23 UTC
