### ISSUE TITLE
Submit forms that expect a click event on a certain DOM element

### ISSUE THREAD

**Issue by shtrom** [passff/passff#358] opened 2018-08-23 04:01 UTC
### General information. Describe your environment

- Versions
  - Operating system: ArchLinux / OS X
  - Browser: Firefox 61.0.2
  - PassFF: 1.5
  - Host app: 1.0.1 & 1.0.2 (just tested)

Status line output: `[12:11:17] show -> (0) no error message`

- Messages in the web console:  nothing
- Using an OpenPGP smart card

---

### Actual behaviour
This has been happening with more and more sites, including the AWS console login: Selecting `Fill & Submit` from the main window, or selecting the equivalent icon (paper aeroplane) from the P menu, the fields complete fine, the form is submitted, but it comes back with an error message which is the same as if the fields hadn't been completed.

Selecting `Fill` or the pencil icon, then manually submitting works fine.

### Expected behaviour
What should happen instead?
Login succeeds after `Fill and Submit`

### Steps to reproduce the behaviour
1. Go to https://console.aws.amazon.com/console/home
2. Click on P, select the plane icon for the AWS credential
3. Received a bad request
```json
{"state":"FAIL","properties":{"Message":"Invalid request","Title":"Bad Request","header":"Bad Request","text":"Invalid request"}}
```

**Comment by tuxor1337** [comment] 2018-08-23 07:52
I can only reproduce this as an issue with the input menu (not when choosing "Fill and submit" from the toolbar menu). For the case of the input menu, there was a race condition that is fixed in c801f42 - can you confirm?

**Comment by shtrom** [comment] 2018-08-23 12:58
This seems to fix it for some sites, but notably not the AWS console. Also, I have double-checked and can confirm that it also happens from the menu with Fill & Submit (with the extension built from c801f42 in ff-dev).

**Comment by tuxor1337** [comment] 2018-08-23 15:54
Are we talking about the same login field on AWS? This is what it looks like for me: 
![screenshot](https://user-images.githubusercontent.com/1518387/44536735-6e2a4200-a6fd-11e8-8a0e-2d53a399dba7.png)
And pressing "Fill" (without submit) already fails for me. But you say, the fill functionality works for you?

**Comment by tuxor1337** [comment] 2018-08-23 16:15
Commit e4f739d fixes my issue regarding the fill functionality.

However, there is no `<form>` and no password input on this page, so submit will not work with our current approach which is: We check for a password input, take that input's form and try submitting this form. If there's no password input in the first place, nothing is submitted. If there's a password input but not form, nothing is submitted. Etc.

I'm not sure we can support this kind of login form, because we would basically have to guess which button to "click"...

**Comment by shtrom** [comment] 2018-08-24 00:07
Ah, no, wrong page. I'm talking about this one: https://console.aws.amazon.com/console/home.

![screen shot 2018-08-24 at 10 05 22](https://user-images.githubusercontent.com/160280/44558054-657d4e80-a785-11e8-8298-69f8fa5c588c.png)

**Comment by tuxor1337** [comment] 2018-08-24 07:27
If I visit the provided URL, I'm redirected to https://signin.aws.amazon.com/signin?redirect_uri=https%3A%2F%2Fconsole.aws.amazon.com%2Fconsole%2Fhome%3Fstate%3DhashArgs%2523%26isauthcode%3Dtrue&client_id=arn%3Aaws%3Aiam%3A%3A015428540659%3Auser%2Fhomepage&forceMobileApp=0 and I am presented with the login form I showed above.

Maybe, the page you refer to is only accessible for AWS users? I don't have an AWS account, so there's no way for me to reach that login form. Is there any other page on the web with the same issue?

**Comment by drmoose** [comment] 2018-08-28 15:20
@tuxor1337 Enter `444444444444` as the account alias on that single-field sign in page to get redirected to the real one.

**Comment by tuxor1337** [comment] 2018-08-28 15:28
Okay, the problem is, that the blue *Sign In* "button" is not really a "button" in HTML, but an HTML `<a>` anchor element. When the user clicks on it, the page's JavaScript takes over. There is no easy way for PassFF to know that this element is the submit button.

If anybody wants to implement a clever heuristic to find the DOM element that is replacing a real submit button on a given web page, feel free to submit a PR. Otherwise, this issue will probably remain unfixed indefinitely.

**Comment by drmoose** [comment] 2018-08-28 16:20
Faking an "Enter" keypress on the password field is enough to get the desired outcome:

```
passwordField.dispatchEvent(new KeyboardEvent('keydown', { 
    'key': "Enter", 
    'code': '\r', 
    'charCode': 13, 
    'keyCode': 13, 
    'which':13, 
    'bubbles': true, 
    'composed': true, 
    'cancelable': true 
}))
```

That said, any such heuristic will not be able to capture every badly-designed login form out there, to say nothing of those that seem to be intentionally built to thwart password managers. 

One possible solution would be to bake the answer into the pass database somehow. We currently can fill out extra fields using `field: value` in the pass entry. Perhaps we could introduce a syntax for specifying how pass submits. (I say "we" -- if this seems like a worthwhile idea I may be able to find time to PR it this weekend rather than just posting drive-by comments on here).

**Comment by tuxor1337** [comment] 2018-08-28 16:32
Personally, I would avoid as much PassFF-specific syntax in the password store as possible. But if you or somebody else comes up with a clean implementation and documentation, I will probably still accept.

**Comment by shtrom** [comment] 2018-08-28 22:16
Note that AWS was just an example of the problem. I picked it as it was somewhat public, but I see the issue with pretty much all the sites I try to log in, regardless of machine/OS.

I'll try to find a few other better examples.

**Comment by shtrom** [comment] 2018-09-10 05:44
[Actually, all the other site with which I had issue seem to work, so the race condition is fixed, leaving this issue for AWS-like login forms]

**Comment by tuxor1337** [comment] 2024-06-04 11:13
I think this kind of issue is still out of reach. Closing due to inactivity.

**Closed by tuxor1337** 2024-06-04 11:13 UTC
Labels: incompatibility
