### ISSUE TITLE
PassFF broken with forms with 2 pages

### ISSUE THREAD

**Issue by akissz** [passff/passff#448] opened 2020-09-06 23:45 UTC
PassFF does not function with forms with 2 pages, for example all google.com website logins do not function. PassFF plugin only enters the "username" for username and for password. It needs to be separate by using the text box names.

**Comment by tuxor1337** [comment] 2020-09-07 13:16
Duplicate of #398 (see also #445).

**Closed by tuxor1337** 2020-09-07 13:16 UTC
