### ISSUE TITLE
Enter-key behaviour: Open in new tab if not already there

### ISSUE THREAD

**Issue by Trollwut** [passff/passff#221] opened 2017-08-04 20:32 UTC
Hi folks!

I think this would add some convenience. :-)

Ok, so we have an Enter key behaviour "Goto and fill", e.g.
This will open the deposited URL in the current tab and then fill the login forms.

A new behaviour would fit my workflow: "Open in new tab if not already there (and fill)"
If I'm already at the (base?) URL of the password, it should just fill the login forms, done.
If I'm on another site, open the deposited URL in a new tab and then fill the forms.

**Comment by tuxor1337** [comment] 2017-08-04 20:41
Have you tried Shift+Enter? Actually, I don't know whether that's documented anywhere, but it does open the deposited URL in a new tab.

**Comment by Trollwut** [comment] 2017-08-04 22:01
Didn't work for me, but then again my standard behaviour set is just "Fill", so maybe I excluded myself by that. :D

**Comment by Trollwut** [comment] 2017-08-06 16:30
On a side note: Would it be possible to focus the last filled textbox when using the "Fill" option?

For now I have to first lick outside of the login form (which mostly is focussed by default) to circumvent shortkey problems, then let it will and then again click myself on the submit button or at least in a textbox to enter/submit the form.

If it focusses the last filled textbox, I would at least spare one click. :)

**Comment by tuxor1337** [comment] 2017-12-16 01:26
@Trollwut: Given the current user interface of PassFF, would you please clarify which changes you suggest? How and where should the option "Open in new tab if not already there (and fill)" be added?

By the way, with the most recent version of PassFF, you don't have to click outside input fields to circumvent shortkey problems.

**Comment by madduck** [comment] 2017-12-19 10:48
Shift-Enter does not work with the current HEAD (1.06linux @ ef31d27f3d0e2cb9a8b34dd817d489ce178f6894). Shift-Enter does nothing.

**Comment by tuxor1337** [comment] 2017-12-19 12:54
Shift-Enter does work for me with 1.0.6linux. Which version of Firefox are you using?

**Comment by madduck** [comment] 2018-01-14 01:21
I've just tried with 971e2f16310c3996c9b3eb160d2a2311769b6f18 (i.e. 1.1) and shift-enter does *not* work.

Apart, I don't see the need to press shift, really. If I hit "enter" and the current URL doesn't match the one of the top-most entry, then passff could heuristically assume that I want to add "goto" to the actions, open a new tab, go to the URL, and then fill the form, no?

**Comment by tuxor1337** [comment] 2018-01-14 09:20
Shift-Enter does work for me with 1.1. Which version of Firefox are you using?

As to the need to press shift: I don't understand how PassFF should know whether the user wants to open a new tab or use the current tab.

**Comment by madduck** [comment] 2018-01-14 18:16
I'm running 57.0.4 from Debian.

The question of whether to reuse the current tab or open a new tab seems like could be best resolved with a setting. On the other hand, a simple enter on an entry not matching the currently loaded URL could mean "reuse", whereas shift-enter could mean to load the new URL in a new tab?

**Closed** 2018-03-17 16:28 UTC
Labels: enhancement

**Comment by tuxor1337** [comment] 2018-03-20 08:43
I'm on 59.0.1, so maybe that's the problem? Do you try with the latest version from Github? What's you setting for the "Behavior of enter key" in the PassFF preferences?

**Comment by tuxor1337** [comment] 2018-03-20 08:55
I tried with Firefox 57.0.4 (on Ubuntu 16.04) and the latest version from GitHub. I cannot reproduce what you describe, I'm afraid. Please give more details about your PassFF preferences.
