### ISSUE TITLE
Installation steps not working for FF v 56.0.1

### ISSUE THREAD

**Issue by kabads** [passff/passff#239] opened 2017-10-25 08:47 UTC
I've followed the steps (including the handler script), but am just a blank screen when attempting to use passff. To confirm, pass works on the command line. I've installed the passff.py and passff.json files in ~/.mozilla/native-messaging-hosts/ 

Screenshot for output - https://i.imgur.com/o5m2VFo.png

This box remains empty regardless of what action is input (ie. searched).

**Comment by tuxor1337** [comment] 2017-10-25 08:53
Does the path in your passff.json point to the passff.py? Have you marked the passff.py as executable?

**Comment by kabads** [comment] 2017-10-25 19:32
@tuxor1337 - yes to both.

**Comment by semitom** [comment] 2017-10-28 19:12
I have had similar issues in the past. After some debugging I found out that firefox got access denied on `~/.password-store/`, because it was sandboxed (I use firejail). Once fixed it worked fine. So perhaps your firefox can not access `~/.password-store/` for any reason?

**Comment by kabads** [comment] 2017-10-28 20:47
I tried opening up permissions, but still no difference. I think this is a gpg-agent-info problem, but I don't know enough about gpg-agent to fix it.

**Comment by tuxor1337** [comment] 2017-12-14 08:56
@kabads Please confirm that your problem still applies to the latest version from addons.mozilla.org. Furthermore, more information about the rest of your setup would be good. Finally, it would be good to have a debugging log from about:debugging.

**Comment by kabads** [comment] 2017-12-14 10:17
@tuxor1337 I've since switched to another plugin that works flawlessly with FF so I've not spent much time getting this working (I needed something straight away). I have installed the latest add-on from the mozilla site and am getting the same error. (FF version 57.0.2)

**Comment by tuxor1337** [comment] 2017-12-16 01:40
Since there are still no clear instructions on how to reproduce this and the logs don't contain any suspicious output, I'm closing this as "worksforme". Maybe it's an operating system issue? Maybe it's an issue with the specific gpg agent used here? Feel free to reopen once you have step by step instructions on how to reproduce this (complete setup with operating system and preferences etc.).

**Closed by tuxor1337** 2017-12-16 01:40 UTC
Labels: question
