### ISSUE TITLE
Fill at most one login field in each form

### ISSUE THREAD

**Issue by xeruf** [passff/passff#491] opened 2021-09-20 06:44 UTC
### General information. Describe your environment
https://www.namecheap.com/myaccount/login

- Versions
  - Operating system: Arch
  - Browser: Firefox
  - PassFF: 1.12.1
  - Host app: 1.2.1

---

### Actual behaviour
On https://www.namecheap.com/myaccount/login when autofilling an "login" entry, it autofills it into the newsletter at the bottom right, even though in the DOM it is clearly marked as "email". Namecheap refuses login because of that...

### Expected behaviour
It leaves the unknown field empty since there is a clear login field to populate.

**Comment by tuxor1337** [comment] 2021-09-20 07:47
In my opinion, it's bad web design on Namecheap's side to have only one big form for all input fields on the website, even though the login forms and the newsletter form are clearly logically and visually separated.

I do acknowledge, however, that some users might prefer to have PassFF stop filling more fields after having filled one field with their login name. Still, you might end up seeing PassFF filling the wrong field for you a lot if it's only filling the first one it can find.

**Comment by xeruf** [comment] 2021-09-20 10:05
It is bad design indeed, but I had this in other instances where passff suddenly filled out a handful of input fields with totally useless information. It should fill all fields that match per id/whatever with the login name, and if it does not find such a field, fill the first it finds.

**Comment by tuxor1337** [comment] 2021-09-20 11:14
What do you mean by "login name"?

**Comment by xeruf** [comment] 2021-09-20 13:04
The value of `login:` or `user:`, I think I remember the plugin having some special handling for that.

**Comment by tuxor1337** [comment] 2021-09-20 15:47
So, the problem with "the first it finds" is that this might not be the one intended by the user, like in the following screenshot where you have two login forms.
![grafik](https://user-images.githubusercontent.com/1518387/134032145-be376c6b-d3a6-44d2-b506-47b627f9a1b3.png)
Because there is actually no way for PassFF to know which one is the correct one, the current approach is to just fill all of the fields. In most situations, this is much more practicable. It's only in exceptional cases with bad web design like this one where we run into problems.

**Comment by xeruf** [comment] 2021-09-21 10:56
Or if it is not a login but a register/address form that contains more fields than just username/password.

Also, here both fields contain the placeholder "Username" through which passff can infer to fill both fields. As said, the restriction to fill only one field holds only when there is no recognized login field.

**Comment by tuxor1337** [comment] 2021-09-21 11:12
PassFF does already restrict filling to "recognized" input elements. However this is not as restrictive as you indicated in your comment above (https://github.com/passff/passff/issues/491#issuecomment-922908261). If we would only consider an input element as "recognized" if the user specified its ID in the pass entry (in the form of `login:` or `user:`), then this would force users to obtain all the input IDs of all websites they are using. This is obviously not desirable.

Instead, you can find the list of key words that are checked in the PassFF preferences ("Login input names"). By default, this list includes "email" because that's a typical login input name. In the case of the namecheap website, unfortunately this matches the input element for the newsletter.

**Comment by tuxor1337** [comment] 2024-05-22 16:49
Closing as duplicate of #484

**Closed by tuxor1337** 2024-05-22 16:49 UTC
Labels: enhancement
