### ISSUE TITLE
Support to configure PASSWORD_STORE_DIR

### ISSUE THREAD

**Issue by shellclear** [passff/passff#459] opened 2020-10-19 02:01 UTC
### General information. Describe your environment

- Versions
  - Operating system: Debian Buster
  - Browser: Firefox 78
  - PassFF: 1.10.3
  - Host app: 1.2.1

Status line output: 
[03:39:04] ls -> (1) Error: password store is empty. Try "pass init". 

### Actual behaviour
I have multiple pass storage directories and multiple Firefox profiles, so cause of that I always need  to start Firefox setting the PASSWORD_STORE_DIR variable to make passFF works.

### Expected behaviour
Having the option to set PASSWORD_STORE_DIR variable in the preferences and this way be able to use different pass storage for each Firefox profile.

### Steps to reproduce the behaviour
1. Create multiple pass storage
2. Create multiple Firefox profiles
3. Trying to use passff

**Comment by tuxor1337** [comment] 2020-10-26 10:27
Closing as duplicate of #376

**Closed by tuxor1337** 2020-10-26 10:27 UTC
Labels: duplicate, enhancement
