### ISSUE TITLE
PassFF with Firefox 58 breaks mattermost login

### ISSUE THREAD

**Issue by nurelin** [passff/passff#304] opened 2018-03-09 09:56 UTC
On Linux, using firefox 58, activating passff prevent login onto mattermost.
Disabling the plugin, login in then reactivating it works.
here is the view I have:
![screenshot-2018-3-9 mattermost](https://user-images.githubusercontent.com/5276274/37201519-3a8a5d70-2388-11e8-8699-a7df77b4ce43.png)

You can try it on [https://oss.mattermost.com/](https://oss.mattermost.com/)

**Comment by tuxor1337** [comment] 2018-03-09 10:16
Duplicate of https://github.com/passff/passff/issues/279 which has been fixed in the latest beta 1.2b (see AMO beta channel).

**Closed by tuxor1337** 2018-03-09 10:16 UTC
Labels: duplicate
