### ISSUE TITLE
Username "undefined" used on certain sites, albeit password is filled correctly

### ISSUE THREAD

**Issue by madduck** [passff/passff#258] opened 2017-12-21 11:03 UTC
Just built from 314b1eb58162a3a3fbb09f0d3be15f199dbbb31f and now on sites like https://www.dkb.de/banking and https://poloniex.com/login, while the password gets filled in properly, the username is given as "undefined". It does work on other sites, like Github though.

**Comment by tuxor1337** [comment] 2017-12-21 13:12
Unfortunately, I can't reproduce this. Is your password store using the following format?

    <the_password>
    login: <the_login>
    url: <the_url>
    <other_inputfield_name>: <inputfield_value>

**Comment by madduck** [comment] 2017-12-21 13:32
I hadn't been using this format, but the implicit one where the username/login was derived from the filename, i.e. `dkb.de/myusername`.

As soon as I add an explicit `login` field, it works again. Fine by me, though I think pass explicitly states that the implicit username is perfectly acceptable usage.

**Comment by tuxor1337** [comment] 2017-12-21 13:38
Yes, it should be working with the `.../dkb.de/myusername` format, I was just asking to narrow down the cause of your issue. Will be fixed in a minute...

**Closed** 2017-12-21 13:40 UTC

**Comment by madduck** [comment] 2017-12-21 13:45
Confirmed fix.
