### ISSUE TITLE
Blank name bug

### ISSUE THREAD

**Issue by akissz** [passff/passff#447] opened 2020-09-06 23:42 UTC
There is a strange bug I found. In passff when you click to add a folder or username and leave the name with only a forward slash, this completely breaks PASS program. And it seems the only way to reset this is to completely delete the password store/directory on the computer and reactive the password store. I think it is also a bug in PASS itself because when you normally type pass in shell it only shows the blank password and you can no longer get back to the normal pass command return display.

**Comment by tuxor1337** [comment] 2020-09-07 13:15
Duplicate of #429

**Closed by tuxor1337** 2020-09-07 13:15 UTC
